import type { PersonaId } from "./personas";

export type ProductCategory = "kit" | "consumable" | "accessory" | "saas";

export type Product = {
  id: string;
  slug: string;
  category: ProductCategory;
  name: string;
  subtitle: string;
  priceEUR: number;
  priceUnit?: string;            // e.g. "one-shot", "/ mois", "/ kg"
  recurring?: { priceEUR: number; period: "mois" | "an" }; // for kits with SaaS bundle
  badge?: string;
  hero: string;                  // /public path
  gallery: string[];             // additional images
  shortPitch: string;            // ≤140 chars marketing line
  longPitch: string;             // 2–3 sentences
  features: { icon: "leaf" | "sensor" | "ai" | "led" | "watering" | "support" | "warranty" | "school" | "esg"; title: string; body: string }[];
  specs: { label: string; value: string }[];
  includes: string[];
  targetPersonas: PersonaId[];   // who it's primarily marketed to
  crossSell: string[];           // product slugs frequently bought together
  complementary: string[];       // slugs that complete the setup
  rating: number;                // 0–5
  reviews: number;
};

const KIT_SAAS: Record<string, { priceEUR: number; period: "mois" | "an" }> = {
  starter:    { priceEUR: 49,  period: "mois" },
  pro:        { priceEUR: 149, period: "mois" },
  enterprise: { priceEUR: 299, period: "mois" },
};

export const products: Product[] = [
  /* ──────────────────────────── KITS ──────────────────────────── */
  {
    id: "kit-starter-mini",
    slug: "kit-starter-mini",
    category: "kit",
    name: "Kit Familial",
    subtitle: "Pour la maison · 3 niveaux · 12 plants · 0,3 m² au sol",
    priceEUR: 449,
    priceUnit: "achat unique",
    recurring: KIT_SAAS.starter,
    badge: "Le plus vendu",
    hero: "/products/packshot-kit-familial.webp",
    gallery: ["/products/packshot-kit-familial.webp", "/products/kit-starter-mini.webp", "/products/scene-iot-sensors.webp", "/products/scene-app-phone.webp"],
    shortPitch: "Un kit compact, autonome, qui passe sur votre plan de travail. Récoltez vos herbes en 21 jours.",
    longPitch:
      "Le compagnon parfait pour débuter l'agriculture connectée. 2 niveaux, 5 capteurs IoT, LED full-spectrum, autonomie d'arrosage 7 jours. Branchez-le, l'IA fait le reste.",
    features: [
      { icon: "sensor",   title: "5 capteurs IoT",       body: "T°, humidité, pH, NPK, luminosité — précision ± 2 %." },
      { icon: "led",      title: "LED full-spectrum",    body: "Cycle automatique 14h/jour, économe (18 W)." },
      { icon: "watering", title: "Arrosage auto 7 j",    body: "Réservoir 4 L, vous partez en vacances tranquille." },
      { icon: "ai",       title: "Copilote IA inclus",   body: "Diagnostic et recommandations en temps réel." },
    ],
    specs: [
      { label: "Dimensions",   value: "45 × 35 × 55 cm" },
      { label: "Surface au sol", value: "0,16 m²" },
      { label: "Capacité",     value: "12 plants · 2 niveaux" },
      { label: "Consommation", value: "≈ 12 kWh / mois" },
      { label: "Garantie",     value: "2 ans pièces & main d'œuvre" },
    ],
    includes: [
      "Cabinet inox + verre",
      "2 plateaux de culture",
      "5 capteurs IoT pré-installés",
      "1 mois de substrat",
      "Sachet 5 variétés (basilic, menthe, roquette, salade, persil)",
      "Hub Wi-Fi",
    ],
    targetPersonas: ["particulier"],
    crossSell: ["consumable-substrate-3l", "consumable-seeds-italian", "accessory-extra-sensor"],
    complementary: ["accessory-led-extender", "consumable-ph-kit", "saas-basic"],
    rating: 4.7,
    reviews: 318,
  },
  {
    id: "kit-pro-duo",
    slug: "kit-pro-duo",
    category: "kit",
    name: "Kit Pro Duo",
    subtitle: "Pour restaurants & PME · 2 colonnes · 0,5 m² au sol",
    priceEUR: 999,
    priceUnit: "achat unique",
    recurring: KIT_SAAS.pro,
    badge: "Restaurants",
    hero: "/products/packshot-pro-duo.webp",
    gallery: ["/products/packshot-pro-duo.webp", "/products/kit-pro-duo.webp", "/products/kit-pro-duo-alt.webp", "/products/scene-iot-sensors.webp"],
    shortPitch: "Deux colonnes, 8 plateaux, 10 capteurs. Une carte ultra-locale signée le matin même.",
    longPitch:
      "Conçu pour la cuisine pro : récolte quotidienne de micro-pousses et d'aromates, ROI moyen 6,2 mois. Co-branding storytelling inclus pour valoriser le circuit court sur votre carte.",
    features: [
      { icon: "sensor",   title: "10 capteurs IoT",      body: "Précision ± 1 % · synchronisation cuisine + bar." },
      { icon: "ai",       title: "Copilote IA Pro",      body: "Suggestions de plats à partir des récoltes du jour." },
      { icon: "support",  title: "Support 9 h – 18 h",   body: "Hotline experts + visite trimestrielle." },
      { icon: "leaf",     title: "Co-branding inclus",   body: "QR menu, PDF storytelling et posts Instagram auto." },
    ],
    specs: [
      { label: "Dimensions",   value: "120 × 50 × 200 cm" },
      { label: "Surface au sol", value: "0,5 m²" },
      { label: "Capacité",     value: "8 plateaux · 80 plants" },
      { label: "Rendement",    value: "≈ 14 kg / mois" },
      { label: "Garantie",     value: "3 ans + SAV prioritaire" },
    ],
    includes: [
      "2 colonnes inox + verre trempé",
      "8 plateaux de culture",
      "10 capteurs IoT haut de gamme",
      "3 mois de substrat & graines pro",
      "Hub + 4G de secours",
      "Onboarding cuisine 2 h",
    ],
    targetPersonas: ["restaurant"],
    crossSell: ["consumable-seeds-chef-pack", "accessory-pro-display", "saas-pro"],
    complementary: ["consumable-substrate-pro", "accessory-co-branding-pack", "kit-enterprise-trio"],
    rating: 4.8,
    reviews: 96,
  },
  {
    id: "kit-pro-trio-wide",
    slug: "kit-pro-trio-wide",
    category: "kit",
    name: "Kit Pro Trio Wide",
    subtitle: "Showroom hall & accueil · base bois · 3 colonnes",
    priceEUR: 1799,
    priceUnit: "achat unique",
    recurring: KIT_SAAS.pro,
    badge: "Hall & accueil",
    hero: "/products/packshot-pro-trio-wide.webp",
    gallery: ["/products/packshot-pro-trio-wide.webp", "/products/kit-pro-trio-wide.webp", "/products/scene-before-after.webp"],
    shortPitch: "Un bar-comptoir vivant pour vos espaces d'accueil. Trois colonnes basses, finition chêne.",
    longPitch:
      "Le format vitrine pour halls, hôtels et brasseries : trois cabinets larges sur socle bois massif, 9 plateaux à hauteur de table. Effet \"wow\" garanti à l'entrée, animation visuelle 24/7.",
    features: [
      { icon: "sensor",  title: "15 capteurs IoT",      body: "Maillage dense pour suivi public + alertes." },
      { icon: "led",     title: "LED Cinema",            body: "Spectre chaud, 95 CRI — vos plantes brillent en photo." },
      { icon: "support", title: "Installation comprise", body: "Pose technique + 1 jour de formation sur site." },
      { icon: "warranty",title: "Garantie 5 ans",        body: "Pièces, main d'œuvre, capteurs." },
    ],
    specs: [
      { label: "Dimensions",   value: "240 × 60 × 130 cm" },
      { label: "Surface au sol", value: "1,4 m²" },
      { label: "Capacité",     value: "9 plateaux · 120 plants" },
      { label: "Socle",        value: "Chêne massif certifié PEFC" },
      { label: "Garantie",     value: "5 ans" },
    ],
    includes: [
      "3 cabinets larges + base bois",
      "9 plateaux pro",
      "15 capteurs IoT",
      "Pack co-branding hôtel/resto",
      "Installation + formation 1 j",
      "6 mois consommables inclus",
    ],
    targetPersonas: ["restaurant", "bureau"],
    crossSell: ["consumable-seeds-chef-pack", "accessory-co-branding-pack", "saas-pro"],
    complementary: ["accessory-pro-display", "consumable-substrate-pro", "kit-enterprise-trio"],
    rating: 4.9,
    reviews: 41,
  },
  {
    id: "kit-enterprise-trio",
    slug: "kit-enterprise-trio",
    category: "kit",
    name: "Kit Enterprise Trio",
    subtitle: "Écoles, sièges, collectivités · 3 colonnes · 4 niveaux",
    priceEUR: 2500,
    priceUnit: "achat unique",
    recurring: KIT_SAAS.enterprise,
    badge: "Écoles & RSE",
    hero: "/products/packshot-enterprise-trio.webp",
    gallery: ["/products/packshot-enterprise-trio.webp", "/products/kit-enterprise-trio.webp", "/products/kit-enterprise-trio-alt.webp", "/products/scene-classroom.webp"],
    shortPitch: "Une vraie ferme verticale pour vos espaces. 12 plateaux, reporting ESG/pédagogie clé en main.",
    longPitch:
      "Notre kit le plus capacitaire : 3 colonnes de 4 niveaux, mode autonomie vacances, API ouverte. Conçu avec des écoles et des DRH pour engager élèves et collaborateurs autour du vivant.",
    features: [
      { icon: "sensor",   title: "20 capteurs IoT pro", body: "Maillage industriel · synchronisation API." },
      { icon: "school",   title: "Mode pédagogique",     body: "Fiches CP→CM2, mode démonstration, autonomie vacances." },
      { icon: "esg",      title: "Reporting ESG",        body: "Export CSV + PDF pour DPEF, DRH, mairies." },
      { icon: "support",  title: "SLA 4 h ouvrées",      body: "Hotline dédiée + interventions prioritaires." },
    ],
    specs: [
      { label: "Dimensions",   value: "330 × 50 × 200 cm" },
      { label: "Surface au sol", value: "1,7 m²" },
      { label: "Capacité",     value: "12 plateaux · 180 plants" },
      { label: "Rendement",    value: "≈ 28 kg / mois" },
      { label: "Conformité",   value: "RGPD · HACCP · CE · ISO 27001" },
    ],
    includes: [
      "3 colonnes 4 niveaux + LED RGB",
      "12 plateaux pro renforcés",
      "20 capteurs IoT industriels",
      "Configuration sur-mesure (pédagogie ou RSE)",
      "Installation + formation 2 j",
      "1 an de consommables inclus",
    ],
    targetPersonas: ["ecole", "bureau"],
    crossSell: ["saas-enterprise", "accessory-pedagogy-pack", "consumable-substrate-pro"],
    complementary: ["accessory-co-branding-pack", "consumable-seeds-school", "kit-pro-trio-wide"],
    rating: 4.9,
    reviews: 28,
  },

  /* ─── Nouveaux kits (packshots) ─── */
  {
    id: "kit-classe-starter",
    slug: "kit-classe-starter",
    category: "kit",
    name: "Kit Classe Starter",
    subtitle: "Pour la classe · format paillasse · 2 plateaux semis + 2 plateaux culture",
    priceEUR: 349,
    priceUnit: "achat unique",
    recurring: KIT_SAAS.starter,
    badge: "Pédagogie",
    hero: "/products/packshot-classe-starter.webp",
    gallery: ["/products/packshot-classe-starter.webp", "/products/scene-classroom.webp", "/products/scene-iot-sensors.webp"],
    shortPitch: "Le kit qui rentre sur une paillasse. Idéal pour faire pousser des semis avec une classe entière.",
    longPitch:
      "Format compact en inox brossé, 2 plateaux semis + 2 plateaux culture, capteurs visibles pour les élèves. Conforme aux normes EN 71 pour usage scolaire.",
    features: [
      { icon: "school",   title: "Conforme EN 71",       body: "Sécurité jouet · agréé établissements scolaires." },
      { icon: "sensor",   title: "Capteurs lisibles",     body: "Affichage gros chiffres pour cycle 2 & 3." },
      { icon: "watering", title: "Réservoir 6 L",         body: "Autonomie 14 j · mode vacances scolaires." },
      { icon: "leaf",     title: "Pack graines inclus",   body: "Radis 21 j, salade, basilic — succès garantis." },
    ],
    specs: [
      { label: "Dimensions",   value: "50 × 38 × 65 cm" },
      { label: "Surface au sol", value: "0,19 m²" },
      { label: "Capacité",     value: "4 plateaux · 32 semis" },
      { label: "Sécurité",     value: "EN 71 · CE · sans BPA" },
      { label: "Garantie",     value: "3 ans + extension école 5 ans" },
    ],
    includes: [
      "Cabinet inox brossé renforcé",
      "4 plateaux pédagogiques",
      "5 capteurs IoT à affichage XL",
      "Pack graines pédagogique (radis, salade, basilic)",
      "Cahier maître + 30 fiches élève",
      "Mode vacances scolaires",
    ],
    targetPersonas: ["ecole"],
    crossSell: ["consumable-seeds-school", "accessory-pedagogy-pack", "saas-enterprise"],
    complementary: ["kit-enterprise-trio", "consumable-substrate-3l"],
    rating: 4.9,
    reviews: 34,
  },
  {
    id: "kit-bureau-compact",
    slug: "kit-bureau-compact",
    category: "kit",
    name: "Kit Bureau Compact",
    subtitle: "Vitrine 3 niveaux pour open-space · format slim",
    priceEUR: 749,
    priceUnit: "achat unique",
    recurring: KIT_SAAS.pro,
    badge: "Bureaux",
    hero: "/products/packshot-bureau-compact.webp",
    gallery: ["/products/packshot-bureau-compact.webp", "/products/scene-app-phone.webp", "/products/scene-iot-sensors.webp"],
    shortPitch: "Le bac à plantes qui transforme votre open-space — silencieux, design, RSE.",
    longPitch:
      "Format vitrine slim 3 niveaux pensé pour les bureaux : silencieux (< 20 dB), design intemporel, intégration RSE. Récolte hebdo pour la pause café.",
    features: [
      { icon: "esg",      title: "Score RSE +",          body: "Bilan carbone & engagement collaborateurs trackés." },
      { icon: "sensor",   title: "8 capteurs discrets",   body: "Intégrés au cadre, mode silencieux." },
      { icon: "ai",       title: "Copilote bureau",       body: "Suggestions de recettes pause-café IA." },
      { icon: "warranty", title: "Garantie 5 ans pro",    body: "Maintenance préventive incluse." },
    ],
    specs: [
      { label: "Dimensions",   value: "70 × 45 × 130 cm" },
      { label: "Surface au sol", value: "0,3 m²" },
      { label: "Capacité",     value: "6 plateaux · 60 plants" },
      { label: "Bruit",        value: "< 20 dB" },
      { label: "Garantie",     value: "5 ans · maintenance incluse" },
    ],
    includes: [
      "Vitrine verre trempé + cadre alu anodisé",
      "6 plateaux design",
      "8 capteurs IoT silencieux",
      "Hub Wi-Fi + 4G secours",
      "Onboarding office manager 1 h",
      "3 mois consommables inclus",
    ],
    targetPersonas: ["bureau"],
    crossSell: ["saas-pro", "accessory-pro-display", "consumable-substrate-3l"],
    complementary: ["kit-pro-trio-wide", "accessory-co-branding-pack"],
    rating: 4.8,
    reviews: 52,
  },
  {
    id: "kit-pro-microgreens",
    slug: "kit-pro-microgreens",
    category: "kit",
    name: "Kit Pro Micro-pousses",
    subtitle: "Cabinet vertical 6 niveaux · production intensive cuisine pro",
    priceEUR: 1499,
    priceUnit: "achat unique",
    recurring: KIT_SAAS.pro,
    badge: "Chefs étoilés",
    hero: "/products/packshot-pro-microgreens.webp",
    gallery: ["/products/packshot-pro-microgreens.webp", "/products/kit-pro-duo.webp", "/products/scene-iot-sensors.webp"],
    shortPitch: "Le format vertical compact qui produit jusqu'à 4 kg de micro-pousses par semaine.",
    longPitch:
      "Inspiré des chambres de pousse pro : 6 niveaux dans 0,4 m² au sol, HACCP-compliant, hygrométrie contrôlée. Le standard des restaurants étoilés.",
    features: [
      { icon: "leaf",     title: "4 kg / semaine",         body: "Production intensive micro-pousses." },
      { icon: "sensor",   title: "Conformité HACCP",        body: "Cellule en inox 304 alimentaire." },
      { icon: "led",      title: "LED haute densité",       body: "200 W éclairage spectre récolte 7–10 j." },
      { icon: "support",  title: "Visite mensuelle",        body: "Technicien Agri One sur site." },
    ],
    specs: [
      { label: "Dimensions",   value: "75 × 55 × 180 cm" },
      { label: "Surface au sol", value: "0,41 m²" },
      { label: "Capacité",     value: "6 plateaux GN 1/1" },
      { label: "Rendement",    value: "≈ 16 kg / mois" },
      { label: "Conformité",   value: "HACCP · inox 304 · CE · IP65" },
    ],
    includes: [
      "Cabinet vertical inox 304",
      "6 plateaux GN 1/1 alimentaires",
      "10 capteurs IoT HACCP",
      "LED dense 200 W full-spectrum",
      "Pack Chef 12 variétés inclus 3 mois",
      "Visite technicien mensuelle 12 mois",
    ],
    targetPersonas: ["restaurant"],
    crossSell: ["consumable-seeds-chef-pack", "saas-pro", "accessory-co-branding-pack"],
    complementary: ["kit-pro-duo", "consumable-substrate-pro", "accessory-pro-display"],
    rating: 5.0,
    reviews: 22,
  },
  {
    id: "kit-serre-connectee",
    slug: "kit-serre-connectee",
    category: "kit",
    name: "Kit Serre Connectée",
    subtitle: "Outdoor balcon · cadre alu + verre · pilotée via app",
    priceEUR: 699,
    priceUnit: "achat unique",
    recurring: KIT_SAAS.starter,
    badge: "Balcon / terrasse",
    hero: "/products/packshot-serre-connectee.webp",
    gallery: ["/products/packshot-serre-connectee.webp", "/products/scene-app-phone.webp", "/products/scene-iot-sensors.webp"],
    shortPitch: "Une vraie petite serre connectée pour balcon — pilotage par l'app, arrosage auto.",
    longPitch:
      "Mini-serre extérieure sur pieds, cadre alu et vitrage trempé, ouverture automatique de toit, arrosage géré à la météo. Pour balcons, terrasses, jardinets.",
    features: [
      { icon: "watering", title: "Arrosage météo-aware",    body: "Lit la météo, ajuste les apports d'eau." },
      { icon: "led",      title: "LED + soleil",             body: "Complément hivernal automatique." },
      { icon: "ai",       title: "App balcon",                body: "Notifications quand cueillir, quand abriter." },
      { icon: "warranty", title: "Verre trempé 4 saisons",    body: "Résiste à −20 °C · grêle classe 3." },
    ],
    specs: [
      { label: "Dimensions",   value: "70 × 45 × 110 cm" },
      { label: "Surface au sol", value: "0,32 m²" },
      { label: "Capacité",     value: "1 grand plateau · 8 plants moyens" },
      { label: "Résistance",   value: "−20 °C · IP65 · grêle classe 3" },
      { label: "Garantie",     value: "3 ans pièces & verre" },
    ],
    includes: [
      "Cadre alu anodisé + verre trempé",
      "Toit motorisé connecté",
      "6 capteurs IoT extérieur",
      "Système d'arrosage 8 L",
      "Pack graines balcon (tomates cerises, basilic, fraises)",
      "Câble extérieur 3 m IP65",
    ],
    targetPersonas: ["particulier"],
    crossSell: ["saas-basic", "consumable-substrate-3l", "consumable-seeds-italian"],
    complementary: ["kit-starter-mini", "accessory-extra-sensor"],
    rating: 4.7,
    reviews: 79,
  },

  /* ──────────────────────────── SaaS abonnements ──────────────────────────── */
  {
    id: "saas-basic", slug: "saas-basic", category: "saas",
    name: "App Basic", subtitle: "Pour particuliers · suivi + IA",
    priceEUR: 49, priceUnit: "/ mois",
    hero: "/products/scene-app-phone.webp", gallery: ["/products/scene-app-phone.webp"],
    shortPitch: "Application complète, copilote IA et communauté Discord.",
    longPitch: "Suivi en temps réel, copilote IA générique, communauté privée. Sans engagement.",
    features: [
      { icon: "ai",    title: "Copilote IA",  body: "Diagnostic et recommandations 24/7." },
      { icon: "leaf",  title: "Communauté",   body: "Discord Agri One + recettes par les utilisateurs." },
    ],
    specs: [
      { label: "Engagement", value: "Sans engagement, résiliable à tout moment" },
      { label: "Capteurs",   value: "Jusqu'à 5 capteurs synchronisés" },
    ],
    includes: ["Application iOS · Android · Web", "Copilote IA générique", "Communauté Discord", "Notifications push intelligentes"],
    targetPersonas: ["particulier"], crossSell: ["kit-starter-mini", "consumable-seeds-italian"], complementary: [],
    rating: 4.6, reviews: 412,
  },
  {
    id: "saas-pro", slug: "saas-pro", category: "saas",
    name: "App Pro", subtitle: "Pour restaurants & PME · analytics + co-branding",
    priceEUR: 149, priceUnit: "/ mois",
    hero: "/products/scene-app-phone.webp", gallery: ["/products/scene-app-phone.webp"],
    shortPitch: "Analytics ROI, calculateur de marge, contenus co-brandés générés par IA.",
    longPitch: "Le mode pro de l'application : analytics financiers, suggestions de plats à partir des récoltes, contenus co-brandés (PDF, posts) générés par l'IA.",
    features: [
      { icon: "ai",     title: "IA recettes",       body: "Suggestions de plats signature à partir de la récolte du jour." },
      { icon: "support",title: "Support prioritaire",body: "9 h – 18 h · hotline + visite trimestrielle." },
    ],
    specs: [
      { label: "Engagement", value: "12 mois renouvelable" },
      { label: "Capteurs",   value: "Jusqu'à 20 capteurs · multi-sites" },
    ],
    includes: ["Tout App Basic", "Analytics ROI & marge", "Calculateur fiche produit", "Pack co-branding (PDF + posts)", "Support hotline 9 h – 18 h"],
    targetPersonas: ["restaurant", "bureau"], crossSell: ["kit-pro-duo", "accessory-co-branding-pack"], complementary: [],
    rating: 4.8, reviews: 124,
  },
  {
    id: "saas-enterprise", slug: "saas-enterprise", category: "saas",
    name: "App Enterprise", subtitle: "Écoles, sièges, multi-sites · API + ESG",
    priceEUR: 299, priceUnit: "/ mois",
    hero: "/products/scene-app-phone.webp", gallery: ["/products/scene-app-phone.webp"],
    shortPitch: "API ouverte, reporting ESG/pédagogie, SLA 4 h ouvrées.",
    longPitch: "L'offre la plus complète pour grands comptes : API ouverte, reporting personnalisé (DPEF, mairies), SLA 4 h ouvrées et onboarding dédié.",
    features: [
      { icon: "esg",     title: "Reporting ESG",   body: "Export CSV/PDF prêt pour DPEF, mairies, parties prenantes." },
      { icon: "school",  title: "Mode pédagogique",body: "Programmes scolaires CP–CM2 intégrés." },
      { icon: "warranty",title: "SLA 4 h ouvrées", body: "Intervention prioritaire, hotline dédiée." },
    ],
    specs: [
      { label: "Engagement", value: "24 mois renouvelable" },
      { label: "Capteurs",   value: "Illimité · multi-sites · API REST" },
    ],
    includes: ["Tout App Pro", "API ouverte (REST + Webhooks)", "Reporting ESG personnalisé", "Onboarding dédié 2 j", "SLA 4 h ouvrées"],
    targetPersonas: ["ecole", "bureau"], crossSell: ["kit-enterprise-trio", "accessory-pedagogy-pack"], complementary: [],
    rating: 4.9, reviews: 38,
  },

  /* ──────────────────────────── Consommables ──────────────────────────── */
  {
    id: "consumable-substrate-3l", slug: "consumable-substrate-3l", category: "consumable",
    name: "Substrat coco premium · 3 L", subtitle: "Fibres de coco compactées · pH neutre",
    priceEUR: 14, priceUnit: "/ unité",
    hero: "/products/scene-iot-sensors.webp", gallery: ["/products/scene-iot-sensors.webp"],
    shortPitch: "Notre substrat préféré pour les herbes du quotidien.",
    longPitch: "Fibres de coco compactées, pH neutre, sans tourbe, certifié bio. Conserve l'humidité jusqu'à 8 jours.",
    features: [
      { icon: "leaf",     title: "100 % naturel",     body: "Sans tourbe, sans pesticide." },
      { icon: "watering", title: "Rétention d'eau",   body: "Jusqu'à 8 jours sans arrosage." },
    ],
    specs: [{ label: "Volume", value: "3 L (1 kg sec, ~9 L hydraté)" }, { label: "Certif.", value: "Ecocert · COSMOS" }],
    includes: ["3 L de substrat coco", "Cuillère de mesure", "Fiche de plantation"],
    targetPersonas: ["particulier", "restaurant", "ecole", "bureau"],
    crossSell: ["consumable-seeds-italian", "kit-starter-mini"], complementary: ["consumable-ph-kit"],
    rating: 4.7, reviews: 642,
  },
  {
    id: "consumable-substrate-pro", slug: "consumable-substrate-pro", category: "consumable",
    name: "Substrat Pro · pack 12 L", subtitle: "Pour usage intensif · cuisine pro / siège",
    priceEUR: 38, priceUnit: "/ pack",
    hero: "/products/scene-iot-sensors.webp", gallery: ["/products/scene-iot-sensors.webp"],
    shortPitch: "Format pro, livré en sac compact, ouvert directement dans la cuisine.",
    longPitch: "Format optimisé pour cuisines pro et collectivités : 12 L compactés en sac de 4 kg, ouverture cleancut.",
    features: [
      { icon: "leaf",     title: "Format pro",      body: "4 × consommation Starter pour 35 % moins cher au litre." },
      { icon: "watering", title: "Compaction usine",body: "Optimisé pour rangement vertical." },
    ],
    specs: [{ label: "Volume", value: "12 L sec (~36 L hydraté)" }, { label: "Certif.", value: "HACCP-friendly" }],
    includes: ["12 L de substrat pro", "Mode d'emploi cuisine", "Fiche traçabilité"],
    targetPersonas: ["restaurant", "ecole", "bureau"],
    crossSell: ["kit-pro-duo", "consumable-seeds-chef-pack"], complementary: ["accessory-pro-display"],
    rating: 4.8, reviews: 119,
  },
  {
    id: "consumable-seeds-italian", slug: "consumable-seeds-italian", category: "consumable",
    name: "Sachet graines · Pasta Lover", subtitle: "Basilic Genovese · origan · persil plat · romarin",
    priceEUR: 19, priceUnit: "/ sachet",
    hero: "/products/scene-iot-sensors.webp", gallery: ["/products/scene-iot-sensors.webp"],
    shortPitch: "Le pack qui suit votre cuisine italienne du dimanche.",
    longPitch: "4 sachets de graines bio, pré-comptées pour vos plateaux Starter. Calendrier d'ensemencement sur l'app.",
    features: [{ icon: "leaf", title: "Bio · origine FR", body: "Graines reproductibles, production Drôme." }],
    specs: [{ label: "Variétés", value: "4 herbes méditerranéennes" }, { label: "Rendement", value: "~ 4 plateaux × 30 j" }],
    includes: ["4 sachets de graines bio", "Calendrier d'ensemencement", "Carte recette pesto signature"],
    targetPersonas: ["particulier", "restaurant"],
    crossSell: ["kit-starter-mini", "consumable-substrate-3l"], complementary: ["consumable-seeds-chef-pack"],
    rating: 4.9, reviews: 287,
  },
  {
    id: "consumable-seeds-chef-pack", slug: "consumable-seeds-chef-pack", category: "consumable",
    name: "Chef Pack · 12 variétés", subtitle: "Pour cuisines pro · micro-pousses & herbes signature",
    priceEUR: 69, priceUnit: "/ pack trimestriel",
    hero: "/products/scene-iot-sensors.webp", gallery: ["/products/scene-iot-sensors.webp"],
    shortPitch: "Les 12 variétés signature pour faire tourner une carte locale toute l'année.",
    longPitch: "Sélectionné avec des chefs étoilés : micro-pousses radis, capucines, basilic Thaï, shiso, oxalis pourpre… Livraison trimestrielle automatique.",
    features: [
      { icon: "leaf",    title: "Sélection chefs",       body: "Co-construit avec des chefs étoilés FR." },
      { icon: "support", title: "Abonnement trimestriel",body: "Vous variez la carte sans y penser." },
    ],
    specs: [{ label: "Variétés", value: "12 (rotation trimestrielle)" }, { label: "Rendement", value: "~ 16 plateaux × 21 j" }],
    includes: ["12 sachets bio", "Fiches dégustation", "Mises en avant Instagram"],
    targetPersonas: ["restaurant"],
    crossSell: ["kit-pro-duo", "saas-pro"], complementary: ["consumable-substrate-pro", "accessory-co-branding-pack"],
    rating: 4.9, reviews: 64,
  },
  {
    id: "consumable-seeds-school", slug: "consumable-seeds-school", category: "consumable",
    name: "Pack pédagogique CP–CM2", subtitle: "Radis 21 j · fraises · salades · capucines",
    priceEUR: 49, priceUnit: "/ pack annuel",
    hero: "/products/scene-classroom.webp", gallery: ["/products/scene-classroom.webp"],
    shortPitch: "Le pack qui suit l'année scolaire avec un cycle de plantation par trimestre.",
    longPitch: "Coordonné aux programmes (cycle de l'eau, photosynthèse, écologie), avec des plantes qui font WOW pour les enfants.",
    features: [
      { icon: "school",  title: "Programmé année scolaire", body: "Septembre → juin, 3 cycles trimestriels." },
      { icon: "leaf",    title: "Plantes \"WOW\" enfants",   body: "Radis 21 j, fraises, capucines comestibles." },
    ],
    specs: [{ label: "Cycles", value: "3 par an" }, { label: "Variétés", value: "8 plantes pédagogiques" }],
    includes: ["8 sachets de graines", "Fiches pédagogiques A4", "Calendrier scolaire imprimé"],
    targetPersonas: ["ecole"],
    crossSell: ["kit-enterprise-trio", "accessory-pedagogy-pack"], complementary: ["consumable-substrate-pro"],
    rating: 5.0, reviews: 22,
  },
  {
    id: "consumable-ph-kit", slug: "consumable-ph-kit", category: "consumable",
    name: "Kit ajustement pH", subtitle: "pH+ · pH− · bandelettes contrôle",
    priceEUR: 24, priceUnit: "/ kit",
    hero: "/products/scene-iot-sensors.webp", gallery: ["/products/scene-iot-sensors.webp"],
    shortPitch: "Le compagnon indispensable pour fiabiliser vos cultures.",
    longPitch: "Deux flacons de correction pH + 50 bandelettes de contrôle. L'app vous alerte quand utiliser quoi.",
    features: [{ icon: "ai", title: "Notifications IA", body: "L'app vous dit exactement combien de gouttes ajouter." }],
    specs: [{ label: "Contenu", value: "2 × 100 ml + 50 bandelettes" }],
    includes: ["Flacon pH+ 100 ml", "Flacon pH− 100 ml", "50 bandelettes pH"],
    targetPersonas: ["particulier", "restaurant", "ecole", "bureau"],
    crossSell: ["consumable-substrate-3l", "accessory-extra-sensor"], complementary: [],
    rating: 4.6, reviews: 401,
  },

  /* ──────────────────────────── Accessoires ──────────────────────────── */
  {
    id: "accessory-extra-sensor", slug: "accessory-extra-sensor", category: "accessory",
    name: "Capteur IoT supplémentaire", subtitle: "T° / Humidité / pH / NPK / Lumière",
    priceEUR: 39, priceUnit: "/ capteur",
    hero: "/products/scene-iot-sensors.webp", gallery: ["/products/scene-iot-sensors.webp"],
    shortPitch: "Densifiez votre maillage capteurs pour des données encore plus fines.",
    longPitch: "Capteur tout-en-un compatible avec tous les kits Agri One. Synchronisation automatique via Bluetooth + Wi-Fi.",
    features: [
      { icon: "sensor",   title: "Plug & play",     body: "Reconnu par l'app en 5 secondes." },
      { icon: "warranty", title: "Garantie 5 ans",  body: "Batterie remplaçable, étanche IP65." },
    ],
    specs: [{ label: "Autonomie", value: "18 mois (CR2477)" }, { label: "Portée", value: "Bluetooth 25 m / Wi-Fi 60 m" }],
    includes: ["1 capteur + housse", "Pile CR2477"],
    targetPersonas: ["particulier", "restaurant", "ecole", "bureau"],
    crossSell: ["consumable-ph-kit", "kit-starter-mini"], complementary: ["accessory-led-extender"],
    rating: 4.7, reviews: 188,
  },
  {
    id: "accessory-led-extender", slug: "accessory-led-extender", category: "accessory",
    name: "Barre LED additionnelle", subtitle: "Full-spectrum · 18 W · plug-and-play",
    priceEUR: 89, priceUnit: "/ barre",
    hero: "/products/scene-before-after.webp", gallery: ["/products/scene-before-after.webp"],
    shortPitch: "Doublez la luminosité pour vos plants à forte demande (tomates, fraises).",
    longPitch: "Barre LED 18 W full-spectrum, contrôlée par l'app pour ajuster cycle et intensité. Indispensable pour fructifier.",
    features: [
      { icon: "led", title: "Full-spectrum",  body: "400 nm – 700 nm, CRI 95." },
      { icon: "ai",  title: "Pilotée par l'IA",body: "Cycle ajusté à la phase de croissance." },
    ],
    specs: [{ label: "Consommation", value: "18 W" }, { label: "Durée de vie", value: "50 000 h" }],
    includes: ["1 barre LED + clips magnétiques", "Câble USB-C 2 m"],
    targetPersonas: ["particulier", "restaurant", "bureau"],
    crossSell: ["kit-starter-mini", "accessory-extra-sensor"], complementary: ["consumable-substrate-3l"],
    rating: 4.8, reviews: 142,
  },
  {
    id: "accessory-co-branding-pack", slug: "accessory-co-branding-pack", category: "accessory",
    name: "Pack Co-branding Pro", subtitle: "QR menu · PDF storytelling · posts Instagram",
    priceEUR: 199, priceUnit: "achat unique",
    hero: "/products/scene-before-after.webp", gallery: ["/products/scene-before-after.webp"],
    shortPitch: "Transformez votre récolte en arme marketing.",
    longPitch: "QR menu animé, fiche storytelling PDF imprimable, calendrier de 24 posts Instagram pré-générés par l'IA.",
    features: [
      { icon: "leaf", title: "QR menu animé",   body: "Vos clients scannent → voient la récolte en live." },
      { icon: "ai",   title: "24 posts IA",      body: "Génération automatique d'un calendrier social." },
    ],
    specs: [{ label: "Formats", value: "PDF, HTML, MP4" }],
    includes: ["QR menu animé hébergé", "PDF storytelling 8 pages", "24 posts Instagram pré-générés"],
    targetPersonas: ["restaurant", "bureau"],
    crossSell: ["kit-pro-duo", "saas-pro"], complementary: [],
    rating: 4.9, reviews: 47,
  },
  {
    id: "accessory-pro-display", slug: "accessory-pro-display", category: "accessory",
    name: "Écran 13'' affichage récolte", subtitle: "Tablette intégrée · animations temps réel",
    priceEUR: 349, priceUnit: "achat unique",
    hero: "/products/scene-app-phone.webp", gallery: ["/products/scene-app-phone.webp"],
    shortPitch: "Affichez en temps réel vos plantations à vos clients.",
    longPitch: "Tablette 13'' intégrée au kit Pro, mode kiosk en boucle : animations, capteurs live, histoire des récoltes.",
    features: [{ icon: "support", title: "Mode kiosk",  body: "Démarrage automatique, anti-vandalisme." }],
    specs: [{ label: "Écran", value: "13'' IPS · 1920×1080" }],
    includes: ["1 tablette + fixation", "Logiciel kiosk", "Animations sur mesure"],
    targetPersonas: ["restaurant", "bureau"],
    crossSell: ["kit-pro-duo", "accessory-co-branding-pack"], complementary: [],
    rating: 4.7, reviews: 31,
  },
  {
    id: "accessory-pedagogy-pack", slug: "accessory-pedagogy-pack", category: "accessory",
    name: "Pack Pédagogie", subtitle: "Fiches CP–CM2 · cahier élève · poster A1",
    priceEUR: 129, priceUnit: "/ classe",
    hero: "/products/scene-classroom.webp", gallery: ["/products/scene-classroom.webp"],
    shortPitch: "Tout ce qu'il faut pour intégrer Agri One au programme scolaire.",
    longPitch: "30 cahiers élève, 1 cahier maître, 1 poster A1 « du semis à l'assiette », fiches pédagogiques alignées sur les programmes.",
    features: [{ icon: "school", title: "Aligné programme", body: "Cycle 2 et 3 — science du vivant." }],
    specs: [{ label: "Contenu", value: "30 cahiers + 1 poster A1 + fiches" }],
    includes: ["30 cahiers élève", "1 cahier maître", "1 poster A1", "Accès portail enseignant"],
    targetPersonas: ["ecole"],
    crossSell: ["kit-enterprise-trio", "consumable-seeds-school"], complementary: ["saas-enterprise"],
    rating: 5.0, reviews: 18,
  },
];

export const getProduct = (slug: string) => products.find((p) => p.slug === slug);
export const getProducts = (filter?: { category?: ProductCategory; persona?: PersonaId }) => {
  return products.filter((p) => {
    if (filter?.category && p.category !== filter.category) return false;
    if (filter?.persona && !p.targetPersonas.includes(filter.persona)) return false;
    return true;
  });
};
